package com.example.flowforge.service.impl;

import com.example.flowforge.dto.AiEdgeDto;
import com.example.flowforge.dto.AiNodeDto;
import com.example.flowforge.dto.response.AiWorkflowResponse;
import com.example.flowforge.entity.*;
import com.example.flowforge.repository.*;
import com.example.flowforge.service.AiWorkflowPersistenceService;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

@Service
public class AiWorkflowPersistenceServiceImpl
        implements AiWorkflowPersistenceService {

    private final WorkflowRepository workflowRepository;
    private final WorkflowNodeRepository workflowNodeRepository;
    private final WorkflowEdgeRepository workflowEdgeRepository;
    private final UserRepository userRepository;

    public AiWorkflowPersistenceServiceImpl(
            WorkflowRepository workflowRepository,
            WorkflowNodeRepository workflowNodeRepository,
            WorkflowEdgeRepository workflowEdgeRepository,
            UserRepository userRepository) {

        this.workflowRepository = workflowRepository;
        this.workflowNodeRepository = workflowNodeRepository;
        this.workflowEdgeRepository = workflowEdgeRepository;
        this.userRepository = userRepository;
    }

    @Override
    public Long saveWorkflow(
            AiWorkflowResponse response) {

        User user =
                userRepository.findById(1L)
                        .orElseThrow();

        Workflow workflow =
                new Workflow();

        workflow.setName(
                response.getWorkflowName());

        workflow.setDescription(
                "Generated by AI Builder");

        workflow.setUser(user);

        workflow =
                workflowRepository.save(workflow);

        Map<Long, WorkflowNode> nodeMap =
                new HashMap<>();

        for (AiNodeDto nodeDto :
                response.getNodes()) {

            WorkflowNode node =
                    new WorkflowNode();

            node.setWorkflow(workflow);

            node.setName(
                    nodeDto.getType());

            node.setType(
                    nodeDto.getType());

            node.setConnectorType(
                    nodeDto.getType());

            node =
                    workflowNodeRepository
                            .save(node);

            nodeMap.put(
                    nodeDto.getId(),
                    node);
        }

        for (AiEdgeDto edgeDto :
                response.getEdges()) {

            WorkflowEdge edge =
                    new WorkflowEdge();

            edge.setSourceNode(
                    nodeMap.get(
                            edgeDto.getSource()));

            edge.setTargetNode(
                    nodeMap.get(
                            edgeDto.getTarget()));

            workflowEdgeRepository
                    .save(edge);
        }

        return workflow.getId();
    }
}